controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_homepage:
    path: /
    controller: App\Controller\WeatherConrollerController::index
api_form:
    path: '/weather/form'
    controller: App\Controller\WeatherConrollerController::index
